blueprint:
  name: Prevent blinds from closing if the window is open
  description: "Prevent blinds from closing if the window is open."
  domain: automation
  input:
    window_sensor:
      name: Window Sensor
      description: The sensor that detects if the window is open
      selector:
        entity:
          domain: binary_sensor
    blind_cover:
      name: Blind
      description: The blind to control
      selector:
        entity:
          domain: cover

trigger:
  - platform: device
    type: opened
    entity_id: !input.window_sensor
    domain: binary_sensor
  - platform: device
    domain: cover
    entity_id: !input.blind_cover
    type: position
    above: 0
    below: 100

condition:
  - condition: device
    type: is_open
    entity_id: !input.window_sensor
    domain: binary_sensor

action:
  - domain: cover
    entity_id: !input.blind_cover
    type: stop
  - domain: cover
    entity_id: !input.blind_cover
    type: open

mode: single
